In [1]:
import numpy as np

# Array Creation

In [2]:
# Basic array creation
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

# Creating arrays with predefined values
zeros_array = np.zeros((2, 3))  # Array of zeros
ones_array = np.ones((3, 2))    # Array of ones
full_array = np.full((2, 2), 7)  # Array filled with 7
identity_matrix = np.eye(3)     # Identity matrix
random_array = np.random.rand(2, 2)  # Array with random values

print("\nZeros Array:")
print(zeros_array)
print("\nOnes Array:")
print(ones_array)
print("\nFull Array:")
print(full_array)
print("\nIdentity Matrix:")
print(identity_matrix)
print("\nRandom Array:")
print(random_array)


1D Array:
[1 2 3 4 5]

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

Full Array:
[[7 7]
 [7 7]]

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array:
[[0.64384852 0.92144052]
 [0.81682509 0.62693536]]


# Array Indexing and Slicing

In [3]:
# Creating a 2D array for indexing and slicing examples
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexing
print("Element at index 2 in array_1d:", array_1d[2])
print("Element at row 1, column 2 in array_2d:", array_2d[1, 2])

# Slicing
print("Sliced 1D array from index 1 to 4:", array_1d[1:4])
print("Sliced 2D array (rows 1 to end, columns 0 to 1):")
print(array_2d[1:, :2])


Element at index 2 in array_1d: 3
Element at row 1, column 2 in array_2d: 6
Sliced 1D array from index 1 to 4: [2 3 4]
Sliced 2D array (rows 1 to end, columns 0 to 1):
[[4 5]
 [7 8]]


# Mathematical Operations

In [4]:

array_sum = array_1d + 10
array_product = array_1d * 2
print("Array after adding 10:")
print(array_sum)
print("Array after multiplying by 2:")
print(array_product)

# Element-wise operations
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
elementwise_sum = np.add(array1, array2)
print("Element-wise sum of array1 and array2:")
print(elementwise_sum)

# Matrix operations
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix1, matrix2)
print("Matrix product of matrix1 and matrix2:")
print(matrix_product)

# Broadcasting
array_a = np.array([1, 2, 3])
array_b = np.array([[4], [5], [6]])
broadcast_result = array_a + array_b
print("Broadcasted addition result:")
print(broadcast_result)


Array after adding 10:
[11 12 13 14 15]
Array after multiplying by 2:
[ 2  4  6  8 10]
Element-wise sum of array1 and array2:
[5 7 9]
Matrix product of matrix1 and matrix2:
[[19 22]
 [43 50]]
Broadcasted addition result:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


# Reshaping Arrays

In [5]:

reshaped_array = np.arange(12).reshape((3, 4))
print("Reshaped array (3x4):")
print(reshaped_array)

flattened_array = reshaped_array.flatten()
print("Flattened array:")
print(flattened_array)



Reshaping Arrays:
Reshaped array (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# Broadcasting and Conditional Operations

In [6]:
# Conditional operations
clipped_array = np.clip(array_1d, 2, 4)
print("Clipped array (values between 2 and 4):")
print(clipped_array)

# Mathematical functions
exp_array = np.exp(array_1d)
sqrt_array = np.sqrt(array_1d)
print("Exponential of array_1d:")
print(exp_array)
print("Square root of array_1d:")
print(sqrt_array)


Clipped array (values between 2 and 4):
[2 2 3 4 4]
Exponential of array_1d:
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Square root of array_1d:
[1.         1.41421356 1.73205081 2.         2.23606798]


# Polynomial Functions

In [7]:
# Polynomial fitting
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 4, 9, 16, 25])
coefficients = np.polyfit(x, y, 2)  # Fit a quadratic polynomial
print("Polynomial coefficients (degree 2):")
print(coefficients)
polynomial_values = np.polyval(coefficients, x)
print("Evaluated polynomial values:")
print(polynomial_values)


Polynomial coefficients (degree 2):
[ 1.00000000e+00 -2.00147285e-14  3.55405155e-14]
Evaluated polynomial values:
[ 1.  4.  9. 16. 25.]


# Random Sampling

In [8]:
# Random sampling
random_samples = np.random.randn(5)  # Samples from a standard normal distribution
print("Random samples from a normal distribution:")
print(random_samples)

choices = np.array([10, 20, 30])
random_choice = np.random.choice(choices, size=3)
print("Random choice from an array:")
print(random_choice)


Random samples from a normal distribution:
[-1.3286573  -0.41753286 -2.011615    0.16743579 -0.71773249]
Random choice from an array:
[30 10 10]
